baseURL = "/"
languageCode = "en-us"
title = "Qihao' Blog"
theme = "hugo-theme-yinyang"
DefaultContentLanguage = "cn"

[author]
  name = "Qihao Wei"
  homepage = "/"

[languages]
  [languages.cn]
    contentDir = "content/"
    languageName = "中文版"
    weight = 1

[params]
headTitle = "Qihao Wei"
#disqus = "joway" # disqus account name
extraHead = ''
mainSections = ["posts"]

[[params.socials]]
name = "GitHub"
link = "https://github.com/qihaowei89/My_Blog"

[[params.socials]]
name = "HomePage"
link = "/"
