---
title: alignment
author: ''
date: '2018-12-12'
slug: alignment
categories:
  - Bioinfomatics
tags:
  - align
  - DNA
  - RNA-seq
  - HISAT2
css: []
description: ''
highlight: yes
index: no
scripts: []
---

## Hisat2   
HISAT2是一个快速和敏感的比对程序，用于将下一代测序读数（全基因组、转录组和外显组测序数据）映射到人类基因组群体（以及单个参考基因组）。基于`BWT for graphs [Sirén et al. 2014]`的方法，设计和实现的一种独创的方法` graph FM index (GFM)`。除了使用代表群体的的全局GFM的index外，HISAT2还使用局部GFM的index，他们共同覆盖整个基因组，每个index代表56Kbp的区域，一共有55000个index。这种新的索引策略称为`层次graph FM index（HGFM）`   


HISAT2中包含人类参考基因组和1230万个常见SNPs位点的index大小为6.2G。SNPs包括1100万个单核苷酸多态性、72.8万缺失和55.5万个插入。这个索引中的插入和删除片段都很小(通常小于20bp)。计划将结构变化(SV)合并到这个索引中。   




**Alignment summary**   

summary for unpaired reads   
```
20000 reads; of these:
  20000 (100.00%) were unpaired; of these:
    1247 (6.24%) aligned 0 times
    18739 (93.69%) aligned exactly 1 time
    14 (0.07%) aligned >1 times
93.77% overall alignment rate
```   



summary for paired reads 
```
10000 reads; of these:
  10000 (100.00%) were paired; of these:
    650 (6.50%) aligned concordantly 0 times
    8823 (88.23%) aligned concordantly exactly 1 time
    527 (5.27%) aligned concordantly >1 times
    ----
    650 pairs aligned concordantly 0 times; of these:
      34 (5.23%) aligned discordantly 1 time
    ----
    616 pairs aligned 0 times concordantly or discordantly; of these:
      1232 mates make up the pairs; of these:
        660 (53.57%) aligned 0 times
        571 (46.35%) aligned exactly 1 time
        1 (0.08%) aligned >1 times
96.70% overall alignment rate
```    

**性能优化**   

`-p `选项使HISAT2启动指定数量的并行线程,每个线程在不同的处理器/核心上运行,使比对吞吐量大约增加为线程数量倍数。



**命令行**   

**设置函数选项**

一些HISAT2选项可以指定函数，而不是单个数字或设置。在这些情况下，用户须指定三个参数：(a)函数类型**F**，(b)常数项**B**和(c)系数**A 。可用的函数类型：常数(C)、线性(L)、平方根(S)和自然对数(G)。参数指定为`F,B,A`-即，函数类型、常数项，系数用逗号分隔，没有空格。常数项和系数可以是负数和/或浮点数。  

例如：    
函数选项指定为L，-0.4，-0.6，表示函数：`f(x) = -0.4 + -0.6 * x`    
函数选项指定为G, 1, 5.4, 表示函数：`f(x) = 1.0 + 5.4 * ln(x)`   

**用法**   
`hisat2 [options]* -x <hisat2-idx> {-1 <m1> -2 <m2> | -U <r> | --sra-acc <SRA accession number>} [-S <sam>]`



















