---
title: R中文件读写函数
author: ''
date: '2018-12-20'
slug: r中文件读写函数
categories:
  - R
tags:
  - file I/O
css: []
description: ''
highlight: yes
index: no
scripts: []
---

**示例数据1 (50 MB)**   
```{r echo=TRUE,include=TRUE,eval=FALSE}
require(data.table)
# Demo speed-up
n = 1e6
DT = data.table( a=sample(1:1000,n,replace=TRUE),
                 b=sample(1:1000,n,replace=TRUE),
                 c=rnorm(n),
                 d=sample(c("foo","bar","baz","qux","quux"),n,replace=TRUE),
                 e=rnorm(n),
                 f=sample(1:1000,n,replace=TRUE) )
DT[2,b:=NA_integer_]
DT[4,c:=NA_real_]
DT[3,d:=NA_character_]
DT[5,d:=""]
DT[2,e:=+Inf]
DT[3,e:=-Inf]

system.time(write.table(DT,"test.csv",sep=",",row.names=FALSE,quote=FALSE))
cat("File size (MB):", round(file.info("test.csv")$size/1024^2),"\n")
# 50 MB (1e6 rows x 6 columns)
```   

**使用`read.csv`读入**
```{r echo=TRUE,include=TRUE,eval=FALSE}
# 第一次读入
system.time(DF1 <- read.csv("test.csv",stringsAsFactors=FALSE))
# 5.8 sec (first time in fresh R session)

# 第二次读入
system.time(DF1 <- read.csv("test.csv",stringsAsFactors=FALSE))
# 3.5 sec (immediate repeat is faster, varies)
```   
**使用`read.table`读入**   
```{r  echo=TRUE,include=TRUE,eval=FALSE}
system.time(DF2 <- read.table("test.csv",header=TRUE,sep=",",quote="",
                              stringsAsFactors=FALSE,comment.char="",nrows=n,
                              colClasses=c("integer","integer","numeric",
                                           "character","numeric","integer")))
# 2.4 sec (consistently). All known tricks and known nrows, see references.
```
**使用`fread`读入**   
```{r  echo=TRUE,include=TRUE,eval=FALSE}
  require(data.table)
  system.time(DT <- fread("test.csv"))
  #  0.13 sec (faster and friendlier)
```

**使用`read.csv.sql`和`read.csv.ffdf`**   
```{r echo=TRUE,include=TRUE,eval=FALSE}
  require(sqldf)
  require(ff)
  system.time(SQLDF <- read.csv.sql("test.csv",dbname=NULL))
  # 2.94 sec (friendly too, good defaults)
  
  system.time(FFDF <- read.csv.ffdf(file="test.csv",nrows=n))
  # 2.97 sec (friendly too, good defaults)

```



**示例数据2 (350 MB)**
```{r echo=TRUE,include=TRUE,eval=FALSE}
l = vector("list",10)
for (i in 1:10) l[[i]] = DT
DTbig = rbindlist(l)
tables()
#     NAME       NROW NCOL  MB        COLS KEY
# 1:    DT  1,000,000    6  34 a,b,c,d,e,f    
# 2: DTbig 10,000,000    6 343 a,b,c,d,e,f    
# Total: 377MB

write.table(DTbig,"testbig.csv",sep=",",row.names=FALSE,quote=FALSE)
# 349MB (10 million rows x 6 columns)
```

```{r echo=TRUE,include=TRUE,eval=FALSE}
# read.table 读入 (~22 sec (varies))
system.time(DF <- read.table("testbig.csv",header=TRUE,sep=",",
                             quote="",stringsAsFactors=FALSE,comment.char="",nrows=1e7,
                             colClasses=c("integer","integer","numeric",
                                          "character","numeric","integer")))

# fread 读入 ( ~1.27 sec)
system.time(DT <- fread("testbig.csv"))
```   


**示例数据3 (airline data)**   
[数据来源](http://stat-computing.org/dataexpo/2009/the-data.html)   
```{r echo=TRUE,include=TRUE,eval=FALSE}
download.file("http://stat-computing.org/dataexpo/2009/2008.csv.bz2", destfile="2008.csv.bz2")
# 109MB (compressed)

system("bunzip2 2008.csv.bz2")
# 658MB (7,009,728 rows x 29 columns)

```

```{r echo=TRUE,include=TRUE,eval=FALSE}
# read.table 读入 (35.4 secs)
colClasses = sapply(read.csv("2008.csv",nrows=200,stringsAsFactors = F),class)
# table(colClasses)
system.time(DF <- read.table("2008.csv", header=TRUE, sep=",", quote="",
                             stringsAsFactors=FALSE,comment.char="",
                             nrows=7009730, colClasses=colClasses))

# fread 读入 (3.84 secs)
system.time(DT <- fread("2008.csv"))

# table(sapply(DT,class)) 不需要担心读入数据的变量类型会出错
```   


**其他参数**   
```{r echo=TRUE,include=TRUE,eval=FALSE}
# 直接读取URL链接中的数据
fread("http://www.stats.ox.ac.uk/pub/datasets/csb/ch11b.dat")

# 直接读取输入数据
fread("A,B\n1,2\n3,4")

# 直接读取复制/粘贴的数据
fread("A,B
      1,2
      3,4
      ")

# 自动检测第一行数据
fread("
      This is perhaps a banner line or two or ten.
      A,B
      1,2
      3,4
      ")

# 自动检测列名是否出现
fread("
      1,2
      3,4
      ")

# read as 'numeric'
DT = fread("A,B\n1.46761e-313,0.5505e-89\n5.12346e-65,9.6456e-43\n")   
DT[,sprintf("%.5E",c(A,B))]


# colClasses 指定读取列的数据类型
data = "A,B,C,D\n1,3,5,7\n2,4,6,8\n"
fread(data, colClasses=c(B="character",C="character",D="character"))  # as read.csv
fread(data, colClasses=list(character=c("B","C","D")))    # saves typing
fread(data, colClasses=list(character=2:4))     # same using column numbers


# drop 删除读取列表的数据类型
fread(data, colClasses=c("B"="NULL","C"="NULL"))   # as read.csv
fread(data, colClasses=list(NULL=c("B","C")))      #
fread(data, drop=c("B","C"))      # same but less typing, easier to read
fread(data, drop=2:3)             # same using column numbers

# select 选择读取指定的列
# (in read.csv you need to work out which to drop)
fread(data, select=c("A","D"))    # less typing, easier to read
fread(data, select=c(1,4))        # same using column numbers


# 跳过空白行
fread("a,b\n1,a\n2,b\n\n\n3,c\n", blank.lines.skip=TRUE)

# 自动填充缺失行
fread("a,b\n1,a\n2\n3,c\n", fill=TRUE)
fread("a,b\n\n1,a\n2\n\n3,c\n\n", fill=TRUE)

# 自动填充缺失行 + 跳过空白行
fread("a,b\n\n1,a\n2\n\n3,c\n\n", fill=TRUE, blank.lines.skip=TRUE)

# 检查列名（无重复，语法有效命名规则）
fread("a b,a b\n1,2\n")
fread("a b,a b\n1,2\n", check.names=TRUE) # no duplicates + syntactically valid names
```   








